################################################################################
# Automatically-generated file. Do not edit!
################################################################################

# Add inputs and outputs from these tool invocations to the build variables 
C_SRCS += \
../glib/glib/bmp.c \
../glib/glib/glib.c \
../glib/glib/glib_bitmap.c \
../glib/glib/glib_circle.c \
../glib/glib/glib_font_narrow_6x8.c \
../glib/glib/glib_font_normal_8x8.c \
../glib/glib/glib_font_number_16x20.c \
../glib/glib/glib_line.c \
../glib/glib/glib_polygon.c \
../glib/glib/glib_rectangle.c \
../glib/glib/glib_string.c 

OBJS += \
./glib/glib/bmp.o \
./glib/glib/glib.o \
./glib/glib/glib_bitmap.o \
./glib/glib/glib_circle.o \
./glib/glib/glib_font_narrow_6x8.o \
./glib/glib/glib_font_normal_8x8.o \
./glib/glib/glib_font_number_16x20.o \
./glib/glib/glib_line.o \
./glib/glib/glib_polygon.o \
./glib/glib/glib_rectangle.o \
./glib/glib/glib_string.o 

C_DEPS += \
./glib/glib/bmp.d \
./glib/glib/glib.d \
./glib/glib/glib_bitmap.d \
./glib/glib/glib_circle.d \
./glib/glib/glib_font_narrow_6x8.d \
./glib/glib/glib_font_normal_8x8.d \
./glib/glib/glib_font_number_16x20.d \
./glib/glib/glib_line.d \
./glib/glib/glib_polygon.d \
./glib/glib/glib_rectangle.d \
./glib/glib/glib_string.d 


# Each subdirectory must supply rules for building sources it contributes
glib/glib/bmp.o: ../glib/glib/bmp.c
	@echo 'Building file: $<'
	@echo 'Invoking: GNU ARM C Compiler'
	arm-none-eabi-gcc -g -gdwarf-2 -mcpu=cortex-m4 -mthumb -std=c99 '-D__HEAP_SIZE=0xD00' '-DHAL_CONFIG=1' '-D__STACK_SIZE=0x800' '-DEFR32BG1B232F256GM56=1' -I"C:\Users\ashis\SimplicityStudio\v4_workspace\HW5" -I"C:\Users\ashis\SimplicityStudio\v4_workspace\HW5\platform\radio\rail_lib\chip\efr32" -I"C:\Users\ashis\SimplicityStudio\v4_workspace\HW5\platform\emdrv\gpiointerrupt\inc" -I"C:\Users\ashis\SimplicityStudio\v4_workspace\HW5\hardware\kit\common\halconfig" -I"C:\Users\ashis\SimplicityStudio\v4_workspace\HW5\hardware\kit\common\bsp" -I"C:\Users\ashis\SimplicityStudio\v4_workspace\HW5\platform\Device\SiliconLabs\EFR32BG1B\Include" -I"C:\Users\ashis\SimplicityStudio\v4_workspace\HW5\platform\CMSIS\Include" -I"C:\Users\ashis\SimplicityStudio\v4_workspace\HW5\hardware\kit\common\drivers" -I"C:\Users\ashis\SimplicityStudio\v4_workspace\HW5\platform\bootloader\api" -I"C:\Users\ashis\SimplicityStudio\v4_workspace\HW5\platform\emlib\src" -I"C:\Users\ashis\SimplicityStudio\v4_workspace\HW5\platform\emlib\inc" -I"C:\Users\ashis\SimplicityStudio\v4_workspace\HW5\platform\emdrv\uartdrv\inc" -I"C:\Users\ashis\SimplicityStudio\v4_workspace\HW5\platform\emdrv\tempdrv\src" -I"C:\Users\ashis\SimplicityStudio\v4_workspace\HW5\platform\halconfig\inc\hal-config" -I"C:\Users\ashis\SimplicityStudio\v4_workspace\HW5\platform\emdrv\sleep\inc" -I"C:\Users\ashis\SimplicityStudio\v4_workspace\HW5\platform\radio\rail_lib\common" -I"C:\Users\ashis\SimplicityStudio\v4_workspace\HW5\protocol\bluetooth_2.7\ble_stack\inc\common" -I"C:\Users\ashis\SimplicityStudio\v4_workspace\HW5\platform\emdrv\common\inc" -I"C:\Users\ashis\SimplicityStudio\v4_workspace\HW5\app\bluetooth_2.7\common\stack_bridge" -I"C:\Users\ashis\SimplicityStudio\v4_workspace\HW5\platform\emdrv\tempdrv\inc" -I"C:\Users\ashis\SimplicityStudio\v4_workspace\HW5\protocol\bluetooth_2.7\ble_stack\inc\soc" -I"C:\Users\ashis\SimplicityStudio\v4_workspace\HW5\platform\emdrv\sleep\src" -I"C:\Users\ashis\SimplicityStudio\v4_workspace\HW5\hardware\kit\EFR32BG1_BRD4302A\config" -I"C:\Users\ashis\SimplicityStudio\v4_workspace\HW5\platform\Device\SiliconLabs\EFR32BG1B\Source\GCC" -I"C:\Users\ashis\SimplicityStudio\v4_workspace\HW5\platform\Device\SiliconLabs\EFR32BG1B\Source" -I"C:\Users\ashis\SimplicityStudio\v4_workspace\HW5\platform\bootloader" -I"C:/C:\SiliconLabs\SimplicityStudio\v4\developer\toolchains\gnu_arm\4.9_2015q3\/lib/gcc/arm-none-eabi/4.9.3/include" -O0 -Wall -c -fmessage-length=0 -ffunction-sections -fdata-sections -mfpu=fpv4-sp-d16 -mfloat-abi=softfp -MMD -MP -MF"glib/glib/bmp.d" -MT"glib/glib/bmp.o" -o "$@" "$<"
	@echo 'Finished building: $<'
	@echo ' '

glib/glib/glib.o: ../glib/glib/glib.c
	@echo 'Building file: $<'
	@echo 'Invoking: GNU ARM C Compiler'
	arm-none-eabi-gcc -g -gdwarf-2 -mcpu=cortex-m4 -mthumb -std=c99 '-D__HEAP_SIZE=0xD00' '-DHAL_CONFIG=1' '-D__STACK_SIZE=0x800' '-DEFR32BG1B232F256GM56=1' -I"C:\Users\ashis\SimplicityStudio\v4_workspace\HW5" -I"C:\Users\ashis\SimplicityStudio\v4_workspace\HW5\platform\radio\rail_lib\chip\efr32" -I"C:\Users\ashis\SimplicityStudio\v4_workspace\HW5\platform\emdrv\gpiointerrupt\inc" -I"C:\Users\ashis\SimplicityStudio\v4_workspace\HW5\hardware\kit\common\halconfig" -I"C:\Users\ashis\SimplicityStudio\v4_workspace\HW5\hardware\kit\common\bsp" -I"C:\Users\ashis\SimplicityStudio\v4_workspace\HW5\platform\Device\SiliconLabs\EFR32BG1B\Include" -I"C:\Users\ashis\SimplicityStudio\v4_workspace\HW5\platform\CMSIS\Include" -I"C:\Users\ashis\SimplicityStudio\v4_workspace\HW5\hardware\kit\common\drivers" -I"C:\Users\ashis\SimplicityStudio\v4_workspace\HW5\platform\bootloader\api" -I"C:\Users\ashis\SimplicityStudio\v4_workspace\HW5\platform\emlib\src" -I"C:\Users\ashis\SimplicityStudio\v4_workspace\HW5\platform\emlib\inc" -I"C:\Users\ashis\SimplicityStudio\v4_workspace\HW5\platform\emdrv\uartdrv\inc" -I"C:\Users\ashis\SimplicityStudio\v4_workspace\HW5\platform\emdrv\tempdrv\src" -I"C:\Users\ashis\SimplicityStudio\v4_workspace\HW5\platform\halconfig\inc\hal-config" -I"C:\Users\ashis\SimplicityStudio\v4_workspace\HW5\platform\emdrv\sleep\inc" -I"C:\Users\ashis\SimplicityStudio\v4_workspace\HW5\platform\radio\rail_lib\common" -I"C:\Users\ashis\SimplicityStudio\v4_workspace\HW5\protocol\bluetooth_2.7\ble_stack\inc\common" -I"C:\Users\ashis\SimplicityStudio\v4_workspace\HW5\platform\emdrv\common\inc" -I"C:\Users\ashis\SimplicityStudio\v4_workspace\HW5\app\bluetooth_2.7\common\stack_bridge" -I"C:\Users\ashis\SimplicityStudio\v4_workspace\HW5\platform\emdrv\tempdrv\inc" -I"C:\Users\ashis\SimplicityStudio\v4_workspace\HW5\protocol\bluetooth_2.7\ble_stack\inc\soc" -I"C:\Users\ashis\SimplicityStudio\v4_workspace\HW5\platform\emdrv\sleep\src" -I"C:\Users\ashis\SimplicityStudio\v4_workspace\HW5\hardware\kit\EFR32BG1_BRD4302A\config" -I"C:\Users\ashis\SimplicityStudio\v4_workspace\HW5\platform\Device\SiliconLabs\EFR32BG1B\Source\GCC" -I"C:\Users\ashis\SimplicityStudio\v4_workspace\HW5\platform\Device\SiliconLabs\EFR32BG1B\Source" -I"C:\Users\ashis\SimplicityStudio\v4_workspace\HW5\platform\bootloader" -I"C:/C:\SiliconLabs\SimplicityStudio\v4\developer\toolchains\gnu_arm\4.9_2015q3\/lib/gcc/arm-none-eabi/4.9.3/include" -O0 -Wall -c -fmessage-length=0 -ffunction-sections -fdata-sections -mfpu=fpv4-sp-d16 -mfloat-abi=softfp -MMD -MP -MF"glib/glib/glib.d" -MT"glib/glib/glib.o" -o "$@" "$<"
	@echo 'Finished building: $<'
	@echo ' '

glib/glib/glib_bitmap.o: ../glib/glib/glib_bitmap.c
	@echo 'Building file: $<'
	@echo 'Invoking: GNU ARM C Compiler'
	arm-none-eabi-gcc -g -gdwarf-2 -mcpu=cortex-m4 -mthumb -std=c99 '-D__HEAP_SIZE=0xD00' '-DHAL_CONFIG=1' '-D__STACK_SIZE=0x800' '-DEFR32BG1B232F256GM56=1' -I"C:\Users\ashis\SimplicityStudio\v4_workspace\HW5" -I"C:\Users\ashis\SimplicityStudio\v4_workspace\HW5\platform\radio\rail_lib\chip\efr32" -I"C:\Users\ashis\SimplicityStudio\v4_workspace\HW5\platform\emdrv\gpiointerrupt\inc" -I"C:\Users\ashis\SimplicityStudio\v4_workspace\HW5\hardware\kit\common\halconfig" -I"C:\Users\ashis\SimplicityStudio\v4_workspace\HW5\hardware\kit\common\bsp" -I"C:\Users\ashis\SimplicityStudio\v4_workspace\HW5\platform\Device\SiliconLabs\EFR32BG1B\Include" -I"C:\Users\ashis\SimplicityStudio\v4_workspace\HW5\platform\CMSIS\Include" -I"C:\Users\ashis\SimplicityStudio\v4_workspace\HW5\hardware\kit\common\drivers" -I"C:\Users\ashis\SimplicityStudio\v4_workspace\HW5\platform\bootloader\api" -I"C:\Users\ashis\SimplicityStudio\v4_workspace\HW5\platform\emlib\src" -I"C:\Users\ashis\SimplicityStudio\v4_workspace\HW5\platform\emlib\inc" -I"C:\Users\ashis\SimplicityStudio\v4_workspace\HW5\platform\emdrv\uartdrv\inc" -I"C:\Users\ashis\SimplicityStudio\v4_workspace\HW5\platform\emdrv\tempdrv\src" -I"C:\Users\ashis\SimplicityStudio\v4_workspace\HW5\platform\halconfig\inc\hal-config" -I"C:\Users\ashis\SimplicityStudio\v4_workspace\HW5\platform\emdrv\sleep\inc" -I"C:\Users\ashis\SimplicityStudio\v4_workspace\HW5\platform\radio\rail_lib\common" -I"C:\Users\ashis\SimplicityStudio\v4_workspace\HW5\protocol\bluetooth_2.7\ble_stack\inc\common" -I"C:\Users\ashis\SimplicityStudio\v4_workspace\HW5\platform\emdrv\common\inc" -I"C:\Users\ashis\SimplicityStudio\v4_workspace\HW5\app\bluetooth_2.7\common\stack_bridge" -I"C:\Users\ashis\SimplicityStudio\v4_workspace\HW5\platform\emdrv\tempdrv\inc" -I"C:\Users\ashis\SimplicityStudio\v4_workspace\HW5\protocol\bluetooth_2.7\ble_stack\inc\soc" -I"C:\Users\ashis\SimplicityStudio\v4_workspace\HW5\platform\emdrv\sleep\src" -I"C:\Users\ashis\SimplicityStudio\v4_workspace\HW5\hardware\kit\EFR32BG1_BRD4302A\config" -I"C:\Users\ashis\SimplicityStudio\v4_workspace\HW5\platform\Device\SiliconLabs\EFR32BG1B\Source\GCC" -I"C:\Users\ashis\SimplicityStudio\v4_workspace\HW5\platform\Device\SiliconLabs\EFR32BG1B\Source" -I"C:\Users\ashis\SimplicityStudio\v4_workspace\HW5\platform\bootloader" -I"C:/C:\SiliconLabs\SimplicityStudio\v4\developer\toolchains\gnu_arm\4.9_2015q3\/lib/gcc/arm-none-eabi/4.9.3/include" -O0 -Wall -c -fmessage-length=0 -ffunction-sections -fdata-sections -mfpu=fpv4-sp-d16 -mfloat-abi=softfp -MMD -MP -MF"glib/glib/glib_bitmap.d" -MT"glib/glib/glib_bitmap.o" -o "$@" "$<"
	@echo 'Finished building: $<'
	@echo ' '

glib/glib/glib_circle.o: ../glib/glib/glib_circle.c
	@echo 'Building file: $<'
	@echo 'Invoking: GNU ARM C Compiler'
	arm-none-eabi-gcc -g -gdwarf-2 -mcpu=cortex-m4 -mthumb -std=c99 '-D__HEAP_SIZE=0xD00' '-DHAL_CONFIG=1' '-D__STACK_SIZE=0x800' '-DEFR32BG1B232F256GM56=1' -I"C:\Users\ashis\SimplicityStudio\v4_workspace\HW5" -I"C:\Users\ashis\SimplicityStudio\v4_workspace\HW5\platform\radio\rail_lib\chip\efr32" -I"C:\Users\ashis\SimplicityStudio\v4_workspace\HW5\platform\emdrv\gpiointerrupt\inc" -I"C:\Users\ashis\SimplicityStudio\v4_workspace\HW5\hardware\kit\common\halconfig" -I"C:\Users\ashis\SimplicityStudio\v4_workspace\HW5\hardware\kit\common\bsp" -I"C:\Users\ashis\SimplicityStudio\v4_workspace\HW5\platform\Device\SiliconLabs\EFR32BG1B\Include" -I"C:\Users\ashis\SimplicityStudio\v4_workspace\HW5\platform\CMSIS\Include" -I"C:\Users\ashis\SimplicityStudio\v4_workspace\HW5\hardware\kit\common\drivers" -I"C:\Users\ashis\SimplicityStudio\v4_workspace\HW5\platform\bootloader\api" -I"C:\Users\ashis\SimplicityStudio\v4_workspace\HW5\platform\emlib\src" -I"C:\Users\ashis\SimplicityStudio\v4_workspace\HW5\platform\emlib\inc" -I"C:\Users\ashis\SimplicityStudio\v4_workspace\HW5\platform\emdrv\uartdrv\inc" -I"C:\Users\ashis\SimplicityStudio\v4_workspace\HW5\platform\emdrv\tempdrv\src" -I"C:\Users\ashis\SimplicityStudio\v4_workspace\HW5\platform\halconfig\inc\hal-config" -I"C:\Users\ashis\SimplicityStudio\v4_workspace\HW5\platform\emdrv\sleep\inc" -I"C:\Users\ashis\SimplicityStudio\v4_workspace\HW5\platform\radio\rail_lib\common" -I"C:\Users\ashis\SimplicityStudio\v4_workspace\HW5\protocol\bluetooth_2.7\ble_stack\inc\common" -I"C:\Users\ashis\SimplicityStudio\v4_workspace\HW5\platform\emdrv\common\inc" -I"C:\Users\ashis\SimplicityStudio\v4_workspace\HW5\app\bluetooth_2.7\common\stack_bridge" -I"C:\Users\ashis\SimplicityStudio\v4_workspace\HW5\platform\emdrv\tempdrv\inc" -I"C:\Users\ashis\SimplicityStudio\v4_workspace\HW5\protocol\bluetooth_2.7\ble_stack\inc\soc" -I"C:\Users\ashis\SimplicityStudio\v4_workspace\HW5\platform\emdrv\sleep\src" -I"C:\Users\ashis\SimplicityStudio\v4_workspace\HW5\hardware\kit\EFR32BG1_BRD4302A\config" -I"C:\Users\ashis\SimplicityStudio\v4_workspace\HW5\platform\Device\SiliconLabs\EFR32BG1B\Source\GCC" -I"C:\Users\ashis\SimplicityStudio\v4_workspace\HW5\platform\Device\SiliconLabs\EFR32BG1B\Source" -I"C:\Users\ashis\SimplicityStudio\v4_workspace\HW5\platform\bootloader" -I"C:/C:\SiliconLabs\SimplicityStudio\v4\developer\toolchains\gnu_arm\4.9_2015q3\/lib/gcc/arm-none-eabi/4.9.3/include" -O0 -Wall -c -fmessage-length=0 -ffunction-sections -fdata-sections -mfpu=fpv4-sp-d16 -mfloat-abi=softfp -MMD -MP -MF"glib/glib/glib_circle.d" -MT"glib/glib/glib_circle.o" -o "$@" "$<"
	@echo 'Finished building: $<'
	@echo ' '

glib/glib/glib_font_narrow_6x8.o: ../glib/glib/glib_font_narrow_6x8.c
	@echo 'Building file: $<'
	@echo 'Invoking: GNU ARM C Compiler'
	arm-none-eabi-gcc -g -gdwarf-2 -mcpu=cortex-m4 -mthumb -std=c99 '-D__HEAP_SIZE=0xD00' '-DHAL_CONFIG=1' '-D__STACK_SIZE=0x800' '-DEFR32BG1B232F256GM56=1' -I"C:\Users\ashis\SimplicityStudio\v4_workspace\HW5" -I"C:\Users\ashis\SimplicityStudio\v4_workspace\HW5\platform\radio\rail_lib\chip\efr32" -I"C:\Users\ashis\SimplicityStudio\v4_workspace\HW5\platform\emdrv\gpiointerrupt\inc" -I"C:\Users\ashis\SimplicityStudio\v4_workspace\HW5\hardware\kit\common\halconfig" -I"C:\Users\ashis\SimplicityStudio\v4_workspace\HW5\hardware\kit\common\bsp" -I"C:\Users\ashis\SimplicityStudio\v4_workspace\HW5\platform\Device\SiliconLabs\EFR32BG1B\Include" -I"C:\Users\ashis\SimplicityStudio\v4_workspace\HW5\platform\CMSIS\Include" -I"C:\Users\ashis\SimplicityStudio\v4_workspace\HW5\hardware\kit\common\drivers" -I"C:\Users\ashis\SimplicityStudio\v4_workspace\HW5\platform\bootloader\api" -I"C:\Users\ashis\SimplicityStudio\v4_workspace\HW5\platform\emlib\src" -I"C:\Users\ashis\SimplicityStudio\v4_workspace\HW5\platform\emlib\inc" -I"C:\Users\ashis\SimplicityStudio\v4_workspace\HW5\platform\emdrv\uartdrv\inc" -I"C:\Users\ashis\SimplicityStudio\v4_workspace\HW5\platform\emdrv\tempdrv\src" -I"C:\Users\ashis\SimplicityStudio\v4_workspace\HW5\platform\halconfig\inc\hal-config" -I"C:\Users\ashis\SimplicityStudio\v4_workspace\HW5\platform\emdrv\sleep\inc" -I"C:\Users\ashis\SimplicityStudio\v4_workspace\HW5\platform\radio\rail_lib\common" -I"C:\Users\ashis\SimplicityStudio\v4_workspace\HW5\protocol\bluetooth_2.7\ble_stack\inc\common" -I"C:\Users\ashis\SimplicityStudio\v4_workspace\HW5\platform\emdrv\common\inc" -I"C:\Users\ashis\SimplicityStudio\v4_workspace\HW5\app\bluetooth_2.7\common\stack_bridge" -I"C:\Users\ashis\SimplicityStudio\v4_workspace\HW5\platform\emdrv\tempdrv\inc" -I"C:\Users\ashis\SimplicityStudio\v4_workspace\HW5\protocol\bluetooth_2.7\ble_stack\inc\soc" -I"C:\Users\ashis\SimplicityStudio\v4_workspace\HW5\platform\emdrv\sleep\src" -I"C:\Users\ashis\SimplicityStudio\v4_workspace\HW5\hardware\kit\EFR32BG1_BRD4302A\config" -I"C:\Users\ashis\SimplicityStudio\v4_workspace\HW5\platform\Device\SiliconLabs\EFR32BG1B\Source\GCC" -I"C:\Users\ashis\SimplicityStudio\v4_workspace\HW5\platform\Device\SiliconLabs\EFR32BG1B\Source" -I"C:\Users\ashis\SimplicityStudio\v4_workspace\HW5\platform\bootloader" -I"C:/C:\SiliconLabs\SimplicityStudio\v4\developer\toolchains\gnu_arm\4.9_2015q3\/lib/gcc/arm-none-eabi/4.9.3/include" -O0 -Wall -c -fmessage-length=0 -ffunction-sections -fdata-sections -mfpu=fpv4-sp-d16 -mfloat-abi=softfp -MMD -MP -MF"glib/glib/glib_font_narrow_6x8.d" -MT"glib/glib/glib_font_narrow_6x8.o" -o "$@" "$<"
	@echo 'Finished building: $<'
	@echo ' '

glib/glib/glib_font_normal_8x8.o: ../glib/glib/glib_font_normal_8x8.c
	@echo 'Building file: $<'
	@echo 'Invoking: GNU ARM C Compiler'
	arm-none-eabi-gcc -g -gdwarf-2 -mcpu=cortex-m4 -mthumb -std=c99 '-D__HEAP_SIZE=0xD00' '-DHAL_CONFIG=1' '-D__STACK_SIZE=0x800' '-DEFR32BG1B232F256GM56=1' -I"C:\Users\ashis\SimplicityStudio\v4_workspace\HW5" -I"C:\Users\ashis\SimplicityStudio\v4_workspace\HW5\platform\radio\rail_lib\chip\efr32" -I"C:\Users\ashis\SimplicityStudio\v4_workspace\HW5\platform\emdrv\gpiointerrupt\inc" -I"C:\Users\ashis\SimplicityStudio\v4_workspace\HW5\hardware\kit\common\halconfig" -I"C:\Users\ashis\SimplicityStudio\v4_workspace\HW5\hardware\kit\common\bsp" -I"C:\Users\ashis\SimplicityStudio\v4_workspace\HW5\platform\Device\SiliconLabs\EFR32BG1B\Include" -I"C:\Users\ashis\SimplicityStudio\v4_workspace\HW5\platform\CMSIS\Include" -I"C:\Users\ashis\SimplicityStudio\v4_workspace\HW5\hardware\kit\common\drivers" -I"C:\Users\ashis\SimplicityStudio\v4_workspace\HW5\platform\bootloader\api" -I"C:\Users\ashis\SimplicityStudio\v4_workspace\HW5\platform\emlib\src" -I"C:\Users\ashis\SimplicityStudio\v4_workspace\HW5\platform\emlib\inc" -I"C:\Users\ashis\SimplicityStudio\v4_workspace\HW5\platform\emdrv\uartdrv\inc" -I"C:\Users\ashis\SimplicityStudio\v4_workspace\HW5\platform\emdrv\tempdrv\src" -I"C:\Users\ashis\SimplicityStudio\v4_workspace\HW5\platform\halconfig\inc\hal-config" -I"C:\Users\ashis\SimplicityStudio\v4_workspace\HW5\platform\emdrv\sleep\inc" -I"C:\Users\ashis\SimplicityStudio\v4_workspace\HW5\platform\radio\rail_lib\common" -I"C:\Users\ashis\SimplicityStudio\v4_workspace\HW5\protocol\bluetooth_2.7\ble_stack\inc\common" -I"C:\Users\ashis\SimplicityStudio\v4_workspace\HW5\platform\emdrv\common\inc" -I"C:\Users\ashis\SimplicityStudio\v4_workspace\HW5\app\bluetooth_2.7\common\stack_bridge" -I"C:\Users\ashis\SimplicityStudio\v4_workspace\HW5\platform\emdrv\tempdrv\inc" -I"C:\Users\ashis\SimplicityStudio\v4_workspace\HW5\protocol\bluetooth_2.7\ble_stack\inc\soc" -I"C:\Users\ashis\SimplicityStudio\v4_workspace\HW5\platform\emdrv\sleep\src" -I"C:\Users\ashis\SimplicityStudio\v4_workspace\HW5\hardware\kit\EFR32BG1_BRD4302A\config" -I"C:\Users\ashis\SimplicityStudio\v4_workspace\HW5\platform\Device\SiliconLabs\EFR32BG1B\Source\GCC" -I"C:\Users\ashis\SimplicityStudio\v4_workspace\HW5\platform\Device\SiliconLabs\EFR32BG1B\Source" -I"C:\Users\ashis\SimplicityStudio\v4_workspace\HW5\platform\bootloader" -I"C:/C:\SiliconLabs\SimplicityStudio\v4\developer\toolchains\gnu_arm\4.9_2015q3\/lib/gcc/arm-none-eabi/4.9.3/include" -O0 -Wall -c -fmessage-length=0 -ffunction-sections -fdata-sections -mfpu=fpv4-sp-d16 -mfloat-abi=softfp -MMD -MP -MF"glib/glib/glib_font_normal_8x8.d" -MT"glib/glib/glib_font_normal_8x8.o" -o "$@" "$<"
	@echo 'Finished building: $<'
	@echo ' '

glib/glib/glib_font_number_16x20.o: ../glib/glib/glib_font_number_16x20.c
	@echo 'Building file: $<'
	@echo 'Invoking: GNU ARM C Compiler'
	arm-none-eabi-gcc -g -gdwarf-2 -mcpu=cortex-m4 -mthumb -std=c99 '-D__HEAP_SIZE=0xD00' '-DHAL_CONFIG=1' '-D__STACK_SIZE=0x800' '-DEFR32BG1B232F256GM56=1' -I"C:\Users\ashis\SimplicityStudio\v4_workspace\HW5" -I"C:\Users\ashis\SimplicityStudio\v4_workspace\HW5\platform\radio\rail_lib\chip\efr32" -I"C:\Users\ashis\SimplicityStudio\v4_workspace\HW5\platform\emdrv\gpiointerrupt\inc" -I"C:\Users\ashis\SimplicityStudio\v4_workspace\HW5\hardware\kit\common\halconfig" -I"C:\Users\ashis\SimplicityStudio\v4_workspace\HW5\hardware\kit\common\bsp" -I"C:\Users\ashis\SimplicityStudio\v4_workspace\HW5\platform\Device\SiliconLabs\EFR32BG1B\Include" -I"C:\Users\ashis\SimplicityStudio\v4_workspace\HW5\platform\CMSIS\Include" -I"C:\Users\ashis\SimplicityStudio\v4_workspace\HW5\hardware\kit\common\drivers" -I"C:\Users\ashis\SimplicityStudio\v4_workspace\HW5\platform\bootloader\api" -I"C:\Users\ashis\SimplicityStudio\v4_workspace\HW5\platform\emlib\src" -I"C:\Users\ashis\SimplicityStudio\v4_workspace\HW5\platform\emlib\inc" -I"C:\Users\ashis\SimplicityStudio\v4_workspace\HW5\platform\emdrv\uartdrv\inc" -I"C:\Users\ashis\SimplicityStudio\v4_workspace\HW5\platform\emdrv\tempdrv\src" -I"C:\Users\ashis\SimplicityStudio\v4_workspace\HW5\platform\halconfig\inc\hal-config" -I"C:\Users\ashis\SimplicityStudio\v4_workspace\HW5\platform\emdrv\sleep\inc" -I"C:\Users\ashis\SimplicityStudio\v4_workspace\HW5\platform\radio\rail_lib\common" -I"C:\Users\ashis\SimplicityStudio\v4_workspace\HW5\protocol\bluetooth_2.7\ble_stack\inc\common" -I"C:\Users\ashis\SimplicityStudio\v4_workspace\HW5\platform\emdrv\common\inc" -I"C:\Users\ashis\SimplicityStudio\v4_workspace\HW5\app\bluetooth_2.7\common\stack_bridge" -I"C:\Users\ashis\SimplicityStudio\v4_workspace\HW5\platform\emdrv\tempdrv\inc" -I"C:\Users\ashis\SimplicityStudio\v4_workspace\HW5\protocol\bluetooth_2.7\ble_stack\inc\soc" -I"C:\Users\ashis\SimplicityStudio\v4_workspace\HW5\platform\emdrv\sleep\src" -I"C:\Users\ashis\SimplicityStudio\v4_workspace\HW5\hardware\kit\EFR32BG1_BRD4302A\config" -I"C:\Users\ashis\SimplicityStudio\v4_workspace\HW5\platform\Device\SiliconLabs\EFR32BG1B\Source\GCC" -I"C:\Users\ashis\SimplicityStudio\v4_workspace\HW5\platform\Device\SiliconLabs\EFR32BG1B\Source" -I"C:\Users\ashis\SimplicityStudio\v4_workspace\HW5\platform\bootloader" -I"C:/C:\SiliconLabs\SimplicityStudio\v4\developer\toolchains\gnu_arm\4.9_2015q3\/lib/gcc/arm-none-eabi/4.9.3/include" -O0 -Wall -c -fmessage-length=0 -ffunction-sections -fdata-sections -mfpu=fpv4-sp-d16 -mfloat-abi=softfp -MMD -MP -MF"glib/glib/glib_font_number_16x20.d" -MT"glib/glib/glib_font_number_16x20.o" -o "$@" "$<"
	@echo 'Finished building: $<'
	@echo ' '

glib/glib/glib_line.o: ../glib/glib/glib_line.c
	@echo 'Building file: $<'
	@echo 'Invoking: GNU ARM C Compiler'
	arm-none-eabi-gcc -g -gdwarf-2 -mcpu=cortex-m4 -mthumb -std=c99 '-D__HEAP_SIZE=0xD00' '-DHAL_CONFIG=1' '-D__STACK_SIZE=0x800' '-DEFR32BG1B232F256GM56=1' -I"C:\Users\ashis\SimplicityStudio\v4_workspace\HW5" -I"C:\Users\ashis\SimplicityStudio\v4_workspace\HW5\platform\radio\rail_lib\chip\efr32" -I"C:\Users\ashis\SimplicityStudio\v4_workspace\HW5\platform\emdrv\gpiointerrupt\inc" -I"C:\Users\ashis\SimplicityStudio\v4_workspace\HW5\hardware\kit\common\halconfig" -I"C:\Users\ashis\SimplicityStudio\v4_workspace\HW5\hardware\kit\common\bsp" -I"C:\Users\ashis\SimplicityStudio\v4_workspace\HW5\platform\Device\SiliconLabs\EFR32BG1B\Include" -I"C:\Users\ashis\SimplicityStudio\v4_workspace\HW5\platform\CMSIS\Include" -I"C:\Users\ashis\SimplicityStudio\v4_workspace\HW5\hardware\kit\common\drivers" -I"C:\Users\ashis\SimplicityStudio\v4_workspace\HW5\platform\bootloader\api" -I"C:\Users\ashis\SimplicityStudio\v4_workspace\HW5\platform\emlib\src" -I"C:\Users\ashis\SimplicityStudio\v4_workspace\HW5\platform\emlib\inc" -I"C:\Users\ashis\SimplicityStudio\v4_workspace\HW5\platform\emdrv\uartdrv\inc" -I"C:\Users\ashis\SimplicityStudio\v4_workspace\HW5\platform\emdrv\tempdrv\src" -I"C:\Users\ashis\SimplicityStudio\v4_workspace\HW5\platform\halconfig\inc\hal-config" -I"C:\Users\ashis\SimplicityStudio\v4_workspace\HW5\platform\emdrv\sleep\inc" -I"C:\Users\ashis\SimplicityStudio\v4_workspace\HW5\platform\radio\rail_lib\common" -I"C:\Users\ashis\SimplicityStudio\v4_workspace\HW5\protocol\bluetooth_2.7\ble_stack\inc\common" -I"C:\Users\ashis\SimplicityStudio\v4_workspace\HW5\platform\emdrv\common\inc" -I"C:\Users\ashis\SimplicityStudio\v4_workspace\HW5\app\bluetooth_2.7\common\stack_bridge" -I"C:\Users\ashis\SimplicityStudio\v4_workspace\HW5\platform\emdrv\tempdrv\inc" -I"C:\Users\ashis\SimplicityStudio\v4_workspace\HW5\protocol\bluetooth_2.7\ble_stack\inc\soc" -I"C:\Users\ashis\SimplicityStudio\v4_workspace\HW5\platform\emdrv\sleep\src" -I"C:\Users\ashis\SimplicityStudio\v4_workspace\HW5\hardware\kit\EFR32BG1_BRD4302A\config" -I"C:\Users\ashis\SimplicityStudio\v4_workspace\HW5\platform\Device\SiliconLabs\EFR32BG1B\Source\GCC" -I"C:\Users\ashis\SimplicityStudio\v4_workspace\HW5\platform\Device\SiliconLabs\EFR32BG1B\Source" -I"C:\Users\ashis\SimplicityStudio\v4_workspace\HW5\platform\bootloader" -I"C:/C:\SiliconLabs\SimplicityStudio\v4\developer\toolchains\gnu_arm\4.9_2015q3\/lib/gcc/arm-none-eabi/4.9.3/include" -O0 -Wall -c -fmessage-length=0 -ffunction-sections -fdata-sections -mfpu=fpv4-sp-d16 -mfloat-abi=softfp -MMD -MP -MF"glib/glib/glib_line.d" -MT"glib/glib/glib_line.o" -o "$@" "$<"
	@echo 'Finished building: $<'
	@echo ' '

glib/glib/glib_polygon.o: ../glib/glib/glib_polygon.c
	@echo 'Building file: $<'
	@echo 'Invoking: GNU ARM C Compiler'
	arm-none-eabi-gcc -g -gdwarf-2 -mcpu=cortex-m4 -mthumb -std=c99 '-D__HEAP_SIZE=0xD00' '-DHAL_CONFIG=1' '-D__STACK_SIZE=0x800' '-DEFR32BG1B232F256GM56=1' -I"C:\Users\ashis\SimplicityStudio\v4_workspace\HW5" -I"C:\Users\ashis\SimplicityStudio\v4_workspace\HW5\platform\radio\rail_lib\chip\efr32" -I"C:\Users\ashis\SimplicityStudio\v4_workspace\HW5\platform\emdrv\gpiointerrupt\inc" -I"C:\Users\ashis\SimplicityStudio\v4_workspace\HW5\hardware\kit\common\halconfig" -I"C:\Users\ashis\SimplicityStudio\v4_workspace\HW5\hardware\kit\common\bsp" -I"C:\Users\ashis\SimplicityStudio\v4_workspace\HW5\platform\Device\SiliconLabs\EFR32BG1B\Include" -I"C:\Users\ashis\SimplicityStudio\v4_workspace\HW5\platform\CMSIS\Include" -I"C:\Users\ashis\SimplicityStudio\v4_workspace\HW5\hardware\kit\common\drivers" -I"C:\Users\ashis\SimplicityStudio\v4_workspace\HW5\platform\bootloader\api" -I"C:\Users\ashis\SimplicityStudio\v4_workspace\HW5\platform\emlib\src" -I"C:\Users\ashis\SimplicityStudio\v4_workspace\HW5\platform\emlib\inc" -I"C:\Users\ashis\SimplicityStudio\v4_workspace\HW5\platform\emdrv\uartdrv\inc" -I"C:\Users\ashis\SimplicityStudio\v4_workspace\HW5\platform\emdrv\tempdrv\src" -I"C:\Users\ashis\SimplicityStudio\v4_workspace\HW5\platform\halconfig\inc\hal-config" -I"C:\Users\ashis\SimplicityStudio\v4_workspace\HW5\platform\emdrv\sleep\inc" -I"C:\Users\ashis\SimplicityStudio\v4_workspace\HW5\platform\radio\rail_lib\common" -I"C:\Users\ashis\SimplicityStudio\v4_workspace\HW5\protocol\bluetooth_2.7\ble_stack\inc\common" -I"C:\Users\ashis\SimplicityStudio\v4_workspace\HW5\platform\emdrv\common\inc" -I"C:\Users\ashis\SimplicityStudio\v4_workspace\HW5\app\bluetooth_2.7\common\stack_bridge" -I"C:\Users\ashis\SimplicityStudio\v4_workspace\HW5\platform\emdrv\tempdrv\inc" -I"C:\Users\ashis\SimplicityStudio\v4_workspace\HW5\protocol\bluetooth_2.7\ble_stack\inc\soc" -I"C:\Users\ashis\SimplicityStudio\v4_workspace\HW5\platform\emdrv\sleep\src" -I"C:\Users\ashis\SimplicityStudio\v4_workspace\HW5\hardware\kit\EFR32BG1_BRD4302A\config" -I"C:\Users\ashis\SimplicityStudio\v4_workspace\HW5\platform\Device\SiliconLabs\EFR32BG1B\Source\GCC" -I"C:\Users\ashis\SimplicityStudio\v4_workspace\HW5\platform\Device\SiliconLabs\EFR32BG1B\Source" -I"C:\Users\ashis\SimplicityStudio\v4_workspace\HW5\platform\bootloader" -I"C:/C:\SiliconLabs\SimplicityStudio\v4\developer\toolchains\gnu_arm\4.9_2015q3\/lib/gcc/arm-none-eabi/4.9.3/include" -O0 -Wall -c -fmessage-length=0 -ffunction-sections -fdata-sections -mfpu=fpv4-sp-d16 -mfloat-abi=softfp -MMD -MP -MF"glib/glib/glib_polygon.d" -MT"glib/glib/glib_polygon.o" -o "$@" "$<"
	@echo 'Finished building: $<'
	@echo ' '

glib/glib/glib_rectangle.o: ../glib/glib/glib_rectangle.c
	@echo 'Building file: $<'
	@echo 'Invoking: GNU ARM C Compiler'
	arm-none-eabi-gcc -g -gdwarf-2 -mcpu=cortex-m4 -mthumb -std=c99 '-D__HEAP_SIZE=0xD00' '-DHAL_CONFIG=1' '-D__STACK_SIZE=0x800' '-DEFR32BG1B232F256GM56=1' -I"C:\Users\ashis\SimplicityStudio\v4_workspace\HW5" -I"C:\Users\ashis\SimplicityStudio\v4_workspace\HW5\platform\radio\rail_lib\chip\efr32" -I"C:\Users\ashis\SimplicityStudio\v4_workspace\HW5\platform\emdrv\gpiointerrupt\inc" -I"C:\Users\ashis\SimplicityStudio\v4_workspace\HW5\hardware\kit\common\halconfig" -I"C:\Users\ashis\SimplicityStudio\v4_workspace\HW5\hardware\kit\common\bsp" -I"C:\Users\ashis\SimplicityStudio\v4_workspace\HW5\platform\Device\SiliconLabs\EFR32BG1B\Include" -I"C:\Users\ashis\SimplicityStudio\v4_workspace\HW5\platform\CMSIS\Include" -I"C:\Users\ashis\SimplicityStudio\v4_workspace\HW5\hardware\kit\common\drivers" -I"C:\Users\ashis\SimplicityStudio\v4_workspace\HW5\platform\bootloader\api" -I"C:\Users\ashis\SimplicityStudio\v4_workspace\HW5\platform\emlib\src" -I"C:\Users\ashis\SimplicityStudio\v4_workspace\HW5\platform\emlib\inc" -I"C:\Users\ashis\SimplicityStudio\v4_workspace\HW5\platform\emdrv\uartdrv\inc" -I"C:\Users\ashis\SimplicityStudio\v4_workspace\HW5\platform\emdrv\tempdrv\src" -I"C:\Users\ashis\SimplicityStudio\v4_workspace\HW5\platform\halconfig\inc\hal-config" -I"C:\Users\ashis\SimplicityStudio\v4_workspace\HW5\platform\emdrv\sleep\inc" -I"C:\Users\ashis\SimplicityStudio\v4_workspace\HW5\platform\radio\rail_lib\common" -I"C:\Users\ashis\SimplicityStudio\v4_workspace\HW5\protocol\bluetooth_2.7\ble_stack\inc\common" -I"C:\Users\ashis\SimplicityStudio\v4_workspace\HW5\platform\emdrv\common\inc" -I"C:\Users\ashis\SimplicityStudio\v4_workspace\HW5\app\bluetooth_2.7\common\stack_bridge" -I"C:\Users\ashis\SimplicityStudio\v4_workspace\HW5\platform\emdrv\tempdrv\inc" -I"C:\Users\ashis\SimplicityStudio\v4_workspace\HW5\protocol\bluetooth_2.7\ble_stack\inc\soc" -I"C:\Users\ashis\SimplicityStudio\v4_workspace\HW5\platform\emdrv\sleep\src" -I"C:\Users\ashis\SimplicityStudio\v4_workspace\HW5\hardware\kit\EFR32BG1_BRD4302A\config" -I"C:\Users\ashis\SimplicityStudio\v4_workspace\HW5\platform\Device\SiliconLabs\EFR32BG1B\Source\GCC" -I"C:\Users\ashis\SimplicityStudio\v4_workspace\HW5\platform\Device\SiliconLabs\EFR32BG1B\Source" -I"C:\Users\ashis\SimplicityStudio\v4_workspace\HW5\platform\bootloader" -I"C:/C:\SiliconLabs\SimplicityStudio\v4\developer\toolchains\gnu_arm\4.9_2015q3\/lib/gcc/arm-none-eabi/4.9.3/include" -O0 -Wall -c -fmessage-length=0 -ffunction-sections -fdata-sections -mfpu=fpv4-sp-d16 -mfloat-abi=softfp -MMD -MP -MF"glib/glib/glib_rectangle.d" -MT"glib/glib/glib_rectangle.o" -o "$@" "$<"
	@echo 'Finished building: $<'
	@echo ' '

glib/glib/glib_string.o: ../glib/glib/glib_string.c
	@echo 'Building file: $<'
	@echo 'Invoking: GNU ARM C Compiler'
	arm-none-eabi-gcc -g -gdwarf-2 -mcpu=cortex-m4 -mthumb -std=c99 '-D__HEAP_SIZE=0xD00' '-DHAL_CONFIG=1' '-D__STACK_SIZE=0x800' '-DEFR32BG1B232F256GM56=1' -I"C:\Users\ashis\SimplicityStudio\v4_workspace\HW5" -I"C:\Users\ashis\SimplicityStudio\v4_workspace\HW5\platform\radio\rail_lib\chip\efr32" -I"C:\Users\ashis\SimplicityStudio\v4_workspace\HW5\platform\emdrv\gpiointerrupt\inc" -I"C:\Users\ashis\SimplicityStudio\v4_workspace\HW5\hardware\kit\common\halconfig" -I"C:\Users\ashis\SimplicityStudio\v4_workspace\HW5\hardware\kit\common\bsp" -I"C:\Users\ashis\SimplicityStudio\v4_workspace\HW5\platform\Device\SiliconLabs\EFR32BG1B\Include" -I"C:\Users\ashis\SimplicityStudio\v4_workspace\HW5\platform\CMSIS\Include" -I"C:\Users\ashis\SimplicityStudio\v4_workspace\HW5\hardware\kit\common\drivers" -I"C:\Users\ashis\SimplicityStudio\v4_workspace\HW5\platform\bootloader\api" -I"C:\Users\ashis\SimplicityStudio\v4_workspace\HW5\platform\emlib\src" -I"C:\Users\ashis\SimplicityStudio\v4_workspace\HW5\platform\emlib\inc" -I"C:\Users\ashis\SimplicityStudio\v4_workspace\HW5\platform\emdrv\uartdrv\inc" -I"C:\Users\ashis\SimplicityStudio\v4_workspace\HW5\platform\emdrv\tempdrv\src" -I"C:\Users\ashis\SimplicityStudio\v4_workspace\HW5\platform\halconfig\inc\hal-config" -I"C:\Users\ashis\SimplicityStudio\v4_workspace\HW5\platform\emdrv\sleep\inc" -I"C:\Users\ashis\SimplicityStudio\v4_workspace\HW5\platform\radio\rail_lib\common" -I"C:\Users\ashis\SimplicityStudio\v4_workspace\HW5\protocol\bluetooth_2.7\ble_stack\inc\common" -I"C:\Users\ashis\SimplicityStudio\v4_workspace\HW5\platform\emdrv\common\inc" -I"C:\Users\ashis\SimplicityStudio\v4_workspace\HW5\app\bluetooth_2.7\common\stack_bridge" -I"C:\Users\ashis\SimplicityStudio\v4_workspace\HW5\platform\emdrv\tempdrv\inc" -I"C:\Users\ashis\SimplicityStudio\v4_workspace\HW5\protocol\bluetooth_2.7\ble_stack\inc\soc" -I"C:\Users\ashis\SimplicityStudio\v4_workspace\HW5\platform\emdrv\sleep\src" -I"C:\Users\ashis\SimplicityStudio\v4_workspace\HW5\hardware\kit\EFR32BG1_BRD4302A\config" -I"C:\Users\ashis\SimplicityStudio\v4_workspace\HW5\platform\Device\SiliconLabs\EFR32BG1B\Source\GCC" -I"C:\Users\ashis\SimplicityStudio\v4_workspace\HW5\platform\Device\SiliconLabs\EFR32BG1B\Source" -I"C:\Users\ashis\SimplicityStudio\v4_workspace\HW5\platform\bootloader" -I"C:/C:\SiliconLabs\SimplicityStudio\v4\developer\toolchains\gnu_arm\4.9_2015q3\/lib/gcc/arm-none-eabi/4.9.3/include" -O0 -Wall -c -fmessage-length=0 -ffunction-sections -fdata-sections -mfpu=fpv4-sp-d16 -mfloat-abi=softfp -MMD -MP -MF"glib/glib/glib_string.d" -MT"glib/glib/glib_string.o" -o "$@" "$<"
	@echo 'Finished building: $<'
	@echo ' '


