// Copyright 2018 Silicon Laboratories, Inc.
//
//

/********************************************************************
 * Autogenerated file, do not edit.
 *******************************************************************/

#ifndef __GATT_DB_H
#define __GATT_DB_H

#include "bg_gattdb_def.h"

extern const struct bg_gattdb_def bg_gattdb_data;

#define gattdb_service_changed_char             3
#define gattdb_device_name                      7
#define gattdb_ota_control                     19
#define gattdb_heart_rate_measurement          22
#define gattdb_user_control_point              25
#define gattdb_spo2_measurement                29
#define gattdb_alert_message                   33
#define gattdb_immediate_alert                 37

#endif
