// Copyright 2018 Silicon Laboratories, Inc.
//
//

/********************************************************************
 * Autogenerated file, do not edit.
 *******************************************************************/

#ifndef __GATT_DB_H
#define __GATT_DB_H

#include "bg_gattdb_def.h"

extern const struct bg_gattdb_def bg_gattdb_data;

#define gattdb_service_changed_char             3
#define gattdb_device_name                      7
#define gattdb_ota_control                     19
#define gattdb_heart_rate_measurement          22
#define gattdb_body_sensor_location            25
#define gattdb_heart_rate_control_point         27
#define gattdb_plx_spot_check_measurement         30
#define gattdb_plx_continuous_measurement         33
#define gattdb_plx_features                    36
#define gattdb_record_access_control_point         38
#define gattdb_supported_new_alert_category         42
#define gattdb_new_alert                       44
#define gattdb_supported_unread_alert_category         47
#define gattdb_unread_alert_status             49
#define gattdb_alert_notification_control_point         52
#define gattdb_alert_level                     55

#endif
